package internal

const (
	DbInit = `CREATE TABLE IF NOT EXISTS applications
		(id INTEGER PRIMARY KEY AUTOINCREMENT,
		APP_NAME TEXT,
		ACTIVE BOOL DEFAULT 1);
		
		CREATE TABLE IF NOT EXISTS environments
		(id INTEGER PRIMARY KEY AUTOINCREMENT,
		APP_KEY INTEGER NOT NULL,
		APP_ENV STRING NOT NULL,
		WRITE_WITHOUT_PREFIX BOOL DEFAULT 0,
		ACTIVE BOOL DEFAULT 1,
		UNIQUE(APP_KEY, APP_ENV));

		CREATE TABLE IF NOT EXISTS variables
		(id INTEGER PRIMARY KEY AUTOINCREMENT,
		APP_ENV_RECORD INTEGER NOT NULL,
		VAR_NAME TEXT,
		VAR_VALUE TEXT,
		ACTIVE BOOL DEFAULT 1,
		UNIQUE(APP_ENV_RECORD, VAR_NAME));`

	SelectAppValues = `SELECT a.APP_NAME, e.APP_ENV, v.VAR_NAME, v.VAR_VALUE
		FROM applications a
		JOIN environments e on a.id = e.APP_KEY
		JOIN variables v on e.id = v.APP_ENV_RECORD
		WHERE a.ACTIVE = '1' AND v.ACTIVE = '1' AND e.ACTIVE = '1'`
)
